export type NotificationItem = {
  id: string;
  type: 'promotion' | 'text';
  username: string;
  subtitle?: string;
  profileImage: string;
  message?: string;
  promoTitle?: string;
  promoDetails?: string;
  promoDescription?: string;
  buttonText?: string;
};

export const notifications: NotificationItem[] = [
  {
    id: '1',
    type: 'promotion',
    username: 'Shark.11',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: '50% off (up to $30)',
    promoDetails: 'Use by June 3, 2025',
    promoDescription: 'At select salons. Hair products or other items may not be eligible.',
    buttonText: 'Add offer',
  },
  {
    id: '2',
    type: 'text',
    username: 'Abhay.07',
    message: 'Liked your post.',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '3',
    type: 'text',
    username: 'Abhay.07',
    message: 'Started following you.',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '4',
    type: 'text',
    username: 'Shark.11',
    message: 'Tag in new post.',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '5',
    type: 'promotion',
    username: 'Shark.11',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: '50% off (up to $30)',
    promoDetails: 'Use by June 3, 2025',
    promoDescription: 'At select salons. Hair products or other items may not be eligible.',
    buttonText: 'Add offer',
  },
  {
    id: '6',
    type: 'text',
    username: 'StyleMaster.Pro',
    message: 'Commented on your photo.',
    subtitle: 'Professional Stylist',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '7',
    type: 'promotion',
    username: 'EliteBarbers',
    subtitle: 'Premium Barbershop',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'Free Beard Trim',
    promoDetails: 'With any haircut service',
    promoDescription: 'New customers only. Valid until July 15, 2025.',
    buttonText: 'Book Now',
  },
  {
    id: '8',
    type: 'text',
    username: 'HairTrends',
    message: 'Shared your style.',
    subtitle: 'Fashion & Style',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '9',
    type: 'text',
    username: 'CutMaster.Jake',
    message: 'Sent you a message.',
    subtitle: 'Your Barber',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '10',
    type: 'promotion',
    username: 'UrbanCuts',
    subtitle: 'Modern Hair Studio',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'Student Discount 20%',
    promoDetails: 'Show valid student ID',
    promoDescription: 'Available Monday to Thursday. All services included.',
    buttonText: 'Claim Offer',
  },
  {
    id: '11',
    type: 'text',
    username: 'BeardGang',
    message: 'Added you to a group.',
    subtitle: 'Beard Enthusiasts',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '12',
    type: 'text',
    username: 'StyleInspo',
    message: 'Mentioned you in a story.',
    subtitle: 'Style Inspiration',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '13',
    type: 'promotion',
    username: 'ClassicCuts',
    subtitle: 'Traditional Barbershop',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'Loyalty Points Bonus',
    promoDetails: 'Double points this week',
    promoDescription: 'Earn 2x points on all services. Limited time offer.',
    buttonText: 'Learn More',
  },
  {
    id: '14',
    type: 'text',
    username: 'HairGoals',
    message: 'Reacted to your story.',
    subtitle: 'Hair Community',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '15',
    type: 'text',
    username: 'BarberLife',
    message: 'Started following you.',
    subtitle: 'Barber Community',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '16',
    type: 'promotion',
    username: 'PremiumCuts',
    subtitle: 'Luxury Hair Salon',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'VIP Package Deal',
    promoDetails: 'Haircut + Styling + Treatment',
    promoDescription: 'Premium service package at 30% off. Book in advance.',
    buttonText: 'Reserve',
  },
  {
    id: '17',
    type: 'text',
    username: 'StyleSquad',
    message: 'Invited you to an event.',
    subtitle: 'Style Meetup',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '18',
    type: 'text',
    username: 'HairArtists',
    message: 'Liked your portfolio.',
    subtitle: 'Creative Stylists',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '19',
    type: 'promotion',
    username: 'QuickCuts',
    subtitle: 'Express Hair Services',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'Flash Sale - 40% Off',
    promoDetails: 'Today only, 2-6 PM',
    promoDescription: 'Walk-in appointments available. First come, first served.',
    buttonText: 'Visit Now',
  },
  {
    id: '20',
    type: 'text',
    username: 'Trendsetters',
    message: 'Featured your style.',
    subtitle: 'Style Magazine',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '21',
    type: 'text',
    username: 'BarberBrothers',
    message: 'Sent you a friend request.',
    subtitle: 'Barber Network',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '22',
    type: 'promotion',
    username: 'HairTech',
    subtitle: 'Innovation Salon',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'New Product Launch',
    promoDetails: 'Free sample with service',
    promoDescription: 'Try our new organic hair care line. Limited samples available.',
    buttonText: 'Get Sample',
  },
  {
    id: '23',
    type: 'text',
    username: 'StyleMasters',
    message: 'Commented on your video.',
    subtitle: 'Style Experts',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '24',
    type: 'text',
    username: 'HairInnovators',
    message: 'Shared your technique.',
    subtitle: 'Hair Innovation',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '25',
    type: 'promotion',
    username: 'EliteStyle',
    subtitle: 'Premium Styling',
    profileImage: 'https://via.placeholder.com/48',
    promoTitle: 'Anniversary Special',
    promoDetails: '25% off for loyal customers',
    promoDescription: 'Celebrating 5 years! Thank you for your continued support.',
    buttonText: 'Book Anniversary',
  },
]; 