export type NotificationItem = {
  id: string;
  type: 'text';
  username: string;
  subtitle?: string;
  profileImage: string;
  message?: string;
};

export const notifications: NotificationItem[] = [
  {
    id: '1',
    type: 'text',
    username: 'Shark.11',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
    message: 'Posted a new update about salon services.',
  },
  {
    id: '2',
    type: 'text',
    username: 'Abhay.07',
    message: 'Liked your post.',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '3',
    type: 'text',
    username: 'Abhay.07',
    message: 'Started following you.',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '4',
    type: 'text',
    username: 'Shark.11',
    message: 'Tag in new post.',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '5',
    type: 'text',
    username: 'Shark.11',
    subtitle: "Men's hair Salon",
    profileImage: 'https://via.placeholder.com/48',
    message: 'Shared a new promotion for salon services.',
  },
  {
    id: '6',
    type: 'text',
    username: 'StyleMaster.Pro',
    message: 'Commented on your photo.',
    subtitle: 'Professional Stylist',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '7',
    type: 'text',
    username: 'EliteBarbers',
    subtitle: 'Premium Barbershop',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Posted about new services available.',
  },
  {
    id: '8',
    type: 'text',
    username: 'HairTrends',
    message: 'Shared your style.',
    subtitle: 'Fashion & Style',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '9',
    type: 'text',
    username: 'CutMaster.Jake',
    message: 'Sent you a message.',
    subtitle: 'Your Barber',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '10',
    type: 'text',
    username: 'UrbanCuts',
    subtitle: 'Modern Hair Studio',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Announced special student discounts.',
  },
  {
    id: '11',
    type: 'text',
    username: 'BeardGang',
    message: 'Added you to a group.',
    subtitle: 'Beard Enthusiasts',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '12',
    type: 'text',
    username: 'StyleInspo',
    message: 'Mentioned you in a story.',
    subtitle: 'Style Inspiration',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '13',
    type: 'text',
    username: 'ClassicCuts',
    subtitle: 'Traditional Barbershop',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Updated loyalty program benefits.',
  },
  {
    id: '14',
    type: 'text',
    username: 'HairGoals',
    message: 'Reacted to your story.',
    subtitle: 'Hair Community',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '15',
    type: 'text',
    username: 'BarberLife',
    message: 'Started following you.',
    subtitle: 'Barber Community',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '16',
    type: 'text',
    username: 'PremiumCuts',
    subtitle: 'Luxury Hair Salon',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Launched new VIP service packages.',
  },
  {
    id: '17',
    type: 'text',
    username: 'StyleSquad',
    message: 'Invited you to an event.',
    subtitle: 'Style Meetup',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '18',
    type: 'text',
    username: 'HairArtists',
    message: 'Liked your portfolio.',
    subtitle: 'Creative Stylists',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '19',
    type: 'text',
    username: 'QuickCuts',
    subtitle: 'Express Hair Services',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Announced a special flash sale event.',
  },
  {
    id: '20',
    type: 'text',
    username: 'Trendsetters',
    message: 'Featured your style.',
    subtitle: 'Style Magazine',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '21',
    type: 'text',
    username: 'BarberBrothers',
    message: 'Sent you a friend request.',
    subtitle: 'Barber Network',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '22',
    type: 'text',
    username: 'HairTech',
    subtitle: 'Innovation Salon',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Launched new organic hair care products.',
  },
  {
    id: '23',
    type: 'text',
    username: 'StyleMasters',
    message: 'Commented on your video.',
    subtitle: 'Style Experts',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '24',
    type: 'text',
    username: 'HairInnovators',
    message: 'Shared your technique.',
    subtitle: 'Hair Innovation',
    profileImage: 'https://via.placeholder.com/48',
  },
  {
    id: '25',
    type: 'text',
    username: 'EliteStyle',
    subtitle: 'Premium Styling',
    profileImage: 'https://via.placeholder.com/48',
    message: 'Celebrating 5 years anniversary with special offers.',
  },
]; 